apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: gaurav-app
  labels:
    app: gaurav-app
spec:
  type: ClusterIP
  selector:
    app: gaurav-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
